name: msd-raspi-fe

on:
  push:
    branches: master

env:
  IMAGE_NAME: "msdinit/raspi-fe"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login dockerhub
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
      -
        name: Build Image
        run: docker buildx build -t ${IMAGE_NAME} --platform armhf --output "type=image,push=true" .
